### ISSUE TITLE
There's a thread on emacs-devel about including this package into Emacs itself

### ISSUE THREAD

**Issue by ylluminarious** [DarwinAwardWinner/mac-pseudo-daemon#5]
Hi,

I started a thread on `emacs-devel` about this package which can be seen [here.](https://lists.gnu.org/archive/html/emacs-devel/2018-05/msg00292.html) The thread was spurred on by this [pull request,](https://bitbucket.org/mituharu/emacs-mac/pull-requests/2/add-multi-tty-support-to-be-on-par-with) and specifically [this comment.](https://bitbucket.org/mituharu/emacs-mac/pull-requests/2/add-multi-tty-support-to-be-on-par-with/diff#comment-61586501) Basically, I made a couple of patches to include [multi-tty support](https://www.emacswiki.org/emacs/MultiTTYSupport) into the Emacs Mac Port which has lacked multi-tty support until now. Unfortunately, multi-tty support (re)introduces the bug solved by this package so I asked Mitsuharu Yamamoto if he would like to include your package into his fork. He said it would be better off trying to include it into GNU Emacs proper first, and so now there is the aforementioned thread discussing exactly that. Just thought you'd want to be aware of this since it's your package and you may want to chime in on that thread.

Thanks.

**Comment by DarwinAwardWinner** [comment]
Well, for the record, I have no objections to including or adapting this package into Emacs itself, and I have previously signed the necessary copyright assignment paperwork for prior contributions to Emacs.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner That's great! There's also some discussion about potentially moving this functionality into the core, so we'll see what pans out. Should I close this issue or leave it open for now, till there is a decision made about whether this package will be used?

**Comment by DarwinAwardWinner** [comment]
I think we can close this issue, and if you need my input, just cc me into the thread on emacs-devel.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Sounds good.

**Comment by DarwinAwardWinner** [comment]
By the way, did that Emacs thread ever come to a consensus? As before, I'd be happy to get this into Emacs, and happy to do any rewriting necessary to get it there.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner No, sorry, I kinda dropped the ball there. My life has become more hectic over the past couple of years due to other projects taking up my time, along with other difficulties. I just didn't take the necessary time or effort to put my patches into a formal pull request to the Emacs trunk.

I recall having a discussion once with RMS about whether I'd need to sign over my copyright to the FSF, which is something I wasn't too comfortable about. He said that I could put my work in the public domain for each individual contribution I made, but it sounded a bit uncertain. I was worried about this issue and coupled with the other difficulties spinning around in my life, so I just left this alone and I've not yet taken the time to incorporate my changes into Emacs formally. Since Emacs 27 is approaching (I think, I haven't followed the news lately), I'm not even sure whether I'll need to update my patches. I made a blog post about it 8 months ago: https://ylluminarious.github.io/2019/05/23/how-to-fix-the-emacs-mac-port-for-multi-tty-access/

My solution to all this, for the time being, has been to manually apply my patches and compile Emacs, as described in the blog post, and then always make sure to install your package. This has sufficed for me.

But perhaps, if others are interested, _maybe_ I could make time to try and do this again. But I can't make any promises since my life is still rather hectic 😅

**Comment by lonelykid** [comment]
@ylluminarious Hello, it looks like the maintainer of Homebrew port of Emacs Macport build has applied your fix for the multi-tty issue. But unlike the gnu official distribution, the graphical frame cannot use an existing daemon; and closing the last graphical frame close quit the GUI app and daemon server with it. That brings me here, trying to get a hidden frame to keep the app running. But it seems pretty buggy and unusable. Closing a frame no long make the app quit, but ``emacsclient -c`` leads to very weird behaviors. Could you share your build and configuration somewhere?

**Comment by ylluminarious** [comment]
@lonelykid Thanks for telling me. Someone over at the Homebrew port already informed me about that, but I appreciate your telling me.

Could you tell me what specific issues you're having with `emacsclient -c`? I have a special frame setup where I always use maximized frames, and it works well for me. I can usually open multiple frames without trouble. I'm not sure how well `mac-pseudo-daemon` works for other workflows / use cases.

**Comment by lonelykid** [comment]
@ylluminarious Thanks for replying. If possible, could you try it in a windowed setup?

1. When you close a graphical frame, a frame will appear and then disappear. This might be the hidden frame. It's annoying but acceptable. 
2. ``emacsclient -c`` does not work when there is no graphical frame left. But if you then click the dock icon, it might shows up multiple frames. Sometimes it even randomly opens multiple frames when you click the dock icon.
3. C-x C-c on one frame might close all the graphical frames.
init.el
````lisp
(server-start)
(add-to-list 'load-path "~/.emacs.d/lisp/mac-pseudo-daemon")
(load "osx-pseudo-daemon")
````
![out](https://user-images.githubusercontent.com/2936633/102360563-2a1f7300-3f80-11eb-8783-ab86162062a0.gif)

**Comment by DarwinAwardWinner** [comment]
@lonelykid The behavior you're describing is all expected based on how mac-pseudo-daemon works. 2 happens because the app is hidden (as if you had pressed Cmd+H on any app, and creating a frame does not un-hide it. You might be able to fix this by adding a hook that un-hides and activates Emacs whenever a frame is created:

```elisp
(add-hook
 'after-make-frame-functions
 (lambda (frm)
   (when (featurep 'ns)
     (ignore-errors
       (ns-hide-emacs 'activate)))))
```

Note that I have not tested this, and there may be some unexpected side effects.

3 is standard emacs behavior; C-x C-c when not running from an emacs client runs `save-buffers-kill-emacs`, which of course kills all frames. You could rebind this to `delete-frame` if you really want it to only kill the current frame.

**Comment by lonelykid** [comment]
@DarwinAwardWinner Thank you for explanation. The hook does not seem to help.
````
(server-start)
(setq mac-option-modifier 'meta)
(add-to-list 'load-path "~/.emacs.d/lisp/mac-pseudo-daemon")
(load "osx-pseudo-daemon")
(mac-pseudo-daemon-mode)
(add-hook
 'after-make-frame-functions
 (lambda (frm)
   (when (featurep 'ns)
     (ignore-errors
       (ns-hide-emacs 'activate)))))
````
3. ``delete-frame``  works. As you said ``save-buffers-kill-emacs`` runs when not from an emacs client. But I'm running from emacsclient.

I understand this is not what you build the plugin for. actually I can open frame and close frame with no problem when running gnu emacs or emacs-plus. It's only troublesome with the macport build because the app quits with the last frame closing.
